#! /bin/bash -l
#
# lgpo		Startup script for Linux Group Policy Daemon.
#
# 
#
### BEGIN INIT INFO
# Provides:          lgpo
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Should-Start:      
# Should-Stop:       
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Linux Group Policy Daemon
### END INIT INFO


NAME=lgpo
DAEMON=/usr/sbin/lgpod
conf_file='/etc/lgpo.conf'
source "${conf_file}"

. /lib/lsb/init-functions
PATH=/bin:/usr/bin:/sbin:/usr/sbin

[ -x $DAEMON ] || exit 0


start () {
	start-stop-daemon --start --ba --quiet --background --pidfile "${pid_file}" --oknodo --exec "${DAEMON}" -- -d || log_end_msg 1
	log_end_msg 0
}

stop () {
	PID=`cat $pid_file 2>/dev/null`
	start-stop-daemon --stop --quiet --pidfile ${pid_file} --name lgpo
	if [ -e ${pid_file} ]
	then
		kill -9 $PID 2>/dev/null
		rm -f ${pid_file}
	fi
}

case "$1" in
    start)
		log_daemon_msg "Starting Linux Group Policy Daemon" "lgpo"
		start
	;;
    stop)
		log_daemon_msg "Stopping Linux Group Policy" "lgpo"
		stop
	;;
    restart)
		log_daemon_msg "Restarting Linux Group Policy" "lgpo"
		stop
		start
	;;
    *)
		echo "Usage: /etc/init.d/$NAME {start|stop|restart}"
		exit 3
	;;
esac

exit 0

